# Generated by Django 4.1.1 on 2022-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_post_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
