# Generated by Django 4.1.1 on 2022-10-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="/images/placeholder.png",
                null=True,
                upload_to="images",
            ),
        ),
    ]
