# Generated by Django 4.1.1 on 2022-10-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_post_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="blog",
            field=models.BooleanField(default=False),
        ),
    ]
