# Generated by Django 4.1.1 on 2022-10-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_post_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="base.tag"),
        ),
    ]
